### ISSUE TITLE
Research: Determine how OpenZeppelin Voter contract prevents delegate spam

### ISSUE THREAD

**Issue by mootz12** [script3/soroban-governor#1]
Delegated token votes have a potential attack vector where a user can cause a delegated accounts state to grow.

Consider User A who delegates their votes for Token X to User B, and there are a collection of other users who also delegate to User B.

If User A transfers any of Token X, an entry is recorded to mark User B's voting power on the block/timestamp of the transfer.

User A could wash trade token X, causing a transfer to occur at every block.

It wasn't immediately obvious how the OpenZeppelin Voter contract prevents this from happening, or if they take the approach that it isn't economical to commit the attack.

Determine if this is possible, and if not, how the OpenZeppelin Voter contract prevents issues from occurring, and document it here.

### Resources
* OpenZeppelin Voter implementation of transferring voting units: https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/governance/utils/Votes.sol#L176-L188

**Comment by Sifu-ma** [comment]
Governance Process
Voting power is determined based on the number of tokens delegated to each address. This means users must submit a delegation transaction before their tokens will be included in governance votes. Users may either delegate to a third party, or self-delegate if they would like to participate in voting directly.
The basic unit of governance is a proposal, which represents a package of executable code to make specific adjustments to the underlying protocol. To prevent spamming, only users whose voting power exceeds the proposal submission threshold are able to submit proposals. Many protocols set this to 1% of total tokens, but each protocol can select their own preferred value.
An optional proposal delay parameter allows protocols to delay the start of voting for a specified length of time after a proposal is submitted, giving time for users to update their vote delegation
Voting takes place over a predefined voting period determined by the underlying protocol (e.g. Compound has a ~2.5 day voting period, while Uniswap uses a 7 day period). When the voting period ends, the system first checks if the number of yes votes exceed the protocol's quorum threshold (e.g. Compound currently requires 4% of total tokens to vote in support to meet quorum).
If the quorum threshold has been met and the vote gains majority support, the passed proposal is then placed into a timelock queue which delays code execution (this is currently set to 2 days for most governance systems). This timelock is intended as a security measure, allowing users to withdraw funds if they think the proposal is malicious or otherwise unacceptable. However, in contrast to Compound Governor which requires use of a linked timelock to function, OpenZeppelin Governor can be deployed and used without a timelock if desired.
If the proposer's voting power drops below the proposal submission threshold at any time from submission until the voting or time-lock period ends, the proposal can be cancelled. Finally, once the entire process has finished, the proposal can be executed and relevant code or parameter changes are implemented in the protocol. The image below shows the general process flow for proposals (note that the specific timelines shown for each phase correspond with Compound governance, but other protocols can choose different time periods).

**Comment by celestialkylin** [comment]
What's the purpose of recording every voting power change and its corresponding timestamp?  Is it for verifying voting power at proposal voting start? How about a lock mechanism? When user A delegates their part/all votes to user B, they must lock this part/all token X.  they can unlock these token X at anytime except user B is voting on a proposal. So if user B place her/his vote on a proposal, this would make the voting power of user B remain fixed until the proposal voting is end. The contract can simply  store the current voting power at the time of locking and unlocking, eliminating the need to record the every change and 
 its timestamp.

**Comment by Sifu-ma** [comment]
I understand your proposal and its quite legitimate as it gives structure to the process but I think flexibility is the purpose of recording every voting power change and its corresponding timestamp. User A may change their perspective about the proposal at ANY time(even during voting) and decide to withdraw their tokens. Also as mentioned above, OpenZeppelin Governor can be deployed without a timelock if desired, so I think this covers for such instances. Truly decentralised.

**Comment by Sifu-ma** [comment]
Excellent, this actually saves time too... Other reason for recording every voting power change and corresponding timestamp is accountability.

**Comment by celestialkylin** [comment]
All historical changes data are stored on the blockchain ledgers, and anyone can query them for analysis, verifying or auditing. If no utilization requires these data, the contract itself dosen't need to store them.

**Comment by Sifu-ma** [comment]
Take this example:
You need to buy vegetables, where would be the best place to buy them?
Option A: Go buy them at the supermarket
Option B: Go buy them at a grocery shop

**Comment by mootz12** [comment]
Note: removed some comments as they were not relevant to the issue.

OpenZeppelin is able to store the full voter history for two main reasons:

1. They store all voting history in a checkpoint list, which only incurs a read per entry they inspect.
2. They implement optimized binary search to limit the number of entries they are required to inspect.

The code implementations of this can be found here: https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/utils/structs/Checkpoints.sol

Soroban can't do the first option well. Due to fixed costs of reading ledger entries and somewhat strict limits on number of entries read in total, separating each vote checkpoint into a separate record will not be efficient.

However, we can make use of temporary storage to significantly reduce the cost of these entries and prevent them from taking up valuable ledger space once they become irrelevant.
