### ISSUE TITLE
Research: Users changing support on proposal

### ISSUE THREAD

**Issue by Ryang-21** [script3/soroban-governor#5]
The current implementation of the governor allows for a voter to switch their support on a proposal. The purpose of this issue is to determine whether this feature is necessary and what risks it might present.

**Comment by celestialkylin** [comment]
Its hard to say which is better. How about deviding the voting period into two parts? During the first part(~90% for example), voters can change their support. For the remaining ~10%,  only new voters can paticipate, and the existing voters can not change their support. The deviding ratio can be controlled by a parameter.

**Comment by Sifu-ma** [comment]
On one hand, I think its necessary to cover for the small margin of error that might occur. Human is to error and one might accidentally vote YES instead of NO or vice versa. With the feature one will be able to rectify their mistake.
On the other hand, it may not be necessary. There should exit a grace period(between announcement of the proposals and voting)that allows voters to come to a conclusion on what it is they really want. After which voting should commence for the particular proposal with no in-between changes allowed. Similar to what happens during the election of leaders all over the world, just more transparent.

**Comment by Sifu-ma** [comment]
I support the decision
